### ISSUE TITLE
"ble_advertising.py" Importing Error

### ISSUE THREAD

**Issue by quietCoder500** [benevpi/Pico_w_ble_uart#1]
The Problem
----------------------------------------------------------------------------

When ever I attempt to run the [test.py](https://github.com/benevpi/Pico_w_ble_uart/blob/main/test.py) file on my Pico W with the latest [firmware with Wi-Fi and Bluetooth LE](https://datasheets.raspberrypi.com/soft/micropython-firmware-pico-w-130623.uf2?_gl=1*cc6t9f*_ga*MTcwOTI4ODgzMC4xNjgwMjk4OTEz*_ga_22FD70LWDS*MTY4Njg1MDM2MC43LjAuMTY4Njg1MDM2MC4wLjAuMA..) support, I get the following error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ble_uart/__init__.py", line 2, in <module>
ImportError: no module named 'ble_advertising'`

And when I move the package to **/lib** I get: 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/ble_uart/__init__.py", line 2, in <module>
ImportError: no module named 'ble_advertising'`

**Comment by quietCoder500** [comment]
I fixed it. Just add `.` before the `ble_advertising` import.
